spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random

    gateway:
      server:
        webflux:
          routes:
            - id: user-auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/user-auth-service/**

            - id: vehicle-service
              uri: http://localhost:8083
              predicates:
                - Path=/vehicle-service/**

            - id: parking-service
              uri: http://localhost:8084
              predicates:
                - Path=/parking-service/**

            - id: payment-service
              uri: http://localhost:8085
              predicates:
                - Path=/payment-service/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka